//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryFeed.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IFSReportingContext : DbContext
    {
        public IFSReportingContext()
            : base("name=IFSReportingContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblInventoryFeed> tblInventoryFeeds { get; set; }
        public DbSet<tblInventoryFeedProcess> tblInventoryFeedProcesses { get; set; }
        public DbSet<tblInventoryLog> tblInventoryLogs { get; set; } 
        public DbSet<tblInvoiceLinesMaster> tblInvoiceLinesMasters { get; set; }
    }
}
