//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryFeed.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryFeed
    {
        public int if_id { get; set; }
        public string customer_no { get; set; }
        public string filetype_requested { get; set; }
        public string send_protocol { get; set; }
        public string protocol_address { get; set; }
        public string sendtime { get; set; }
        public string sendbuyers_partno { get; set; }
        public string sendaaid_instead_brand_id { get; set; }
        public string fields { get; set; }
        public string includeheaders { get; set; }
        public string sendday { get; set; }
    }
}
