//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryFeed.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceLinesMaster
    {
        public double STATISTIC_NO { get; set; }
        public Nullable<System.DateTime> STATISTIC_DATE { get; set; }
        public Nullable<double> INVOICE_ID { get; set; }
        public Nullable<double> ITEM_ID { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<double> INVOICED_QTY { get; set; }
        public Nullable<double> COST { get; set; }
        public Nullable<double> SALE_UNIT_PRICE { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public Nullable<double> BASE_SALE_UNIT_PRICE { get; set; }
        public Nullable<double> CURR_DISCOUNT { get; set; }
        public Nullable<double> ORDER_DISCOUNT { get; set; }
        public Nullable<double> ORDER_CURR_DISCOUNT { get; set; }
        public Nullable<double> NET_AMOUNT { get; set; }
        public Nullable<double> PRICE_QTY { get; set; }
        public Nullable<double> NET_CURR_AMOUNT { get; set; }
        public Nullable<double> GROSS_AMOUNT { get; set; }
        public Nullable<double> GROSS_CURR_AMOUNT { get; set; }
        public string CATALOG_DESC { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string COUNTRY_DESC { get; set; }
        public string CUST_GRP_DESC { get; set; }
        public string COMPANY_NAME { get; set; }
        public string MARKET_DESC { get; set; }
        public string REGION_DESC { get; set; }
        public string DISTRICT_DESC { get; set; }
        public string SALESMAN { get; set; }
        public string AUTHORIZE_NAME { get; set; }
        public string PRICE_LIST_DESC { get; set; }
        public string ORDER_NO { get; set; }
        public string CATALOG_GROUP_DESC { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string CUST_GRP { get; set; }
        public string CONTRACT { get; set; }
        public string CATALOG_NO { get; set; }
        public string PART_NO { get; set; }
        public string PRICE_LIST_NO { get; set; }
        public string AUTHORIZE_CODE { get; set; }
        public string SALESMAN_CODE { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string REGION_CODE { get; set; }
        public string MARKET_CODE { get; set; }
        public string COMPANY { get; set; }
        public string SALES_UNIT_MEAS { get; set; }
        public string PRICE_UNIT_MEAS { get; set; }
        public string ACCT_CURRENCY_CODE { get; set; }
        public string ORDER_CURRENCY_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string CATALOG_GROUP { get; set; }
        public string PART_DESC { get; set; }
        public string LINE_NO { get; set; }
        public string REL_NO { get; set; }
        public Nullable<double> LINE_ITEM_NO { get; set; }
        public string PAYER_NO { get; set; }
        public string PAYER_NAME { get; set; }
        public string CUSTOMER_PRICE_GROUP { get; set; }
        public string CUSTOMER_PRICE_GRP_DESC { get; set; }
        public Nullable<double> ADDITIONAL_DISCOUNT { get; set; }
        public Nullable<double> ADDITIONAL_CURR_DISCOUNT { get; set; }
        public string BRANCH { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string INVOICE_NO { get; set; }
        public string SERIES_ID { get; set; }
        public string CONDITION_CODE { get; set; }
        public string CONDITION_CODE_DESCRIPTION { get; set; }
        public string OBJID { get; set; }
        public string OBJVERSION { get; set; }
    }
}
